#import pexpect.popen_spawn
import wexpect
try:    
    print('start automation')
    #child = pexpect.popen_spawn.PopenSpawn('python C:\Users\42408\Documents\step2\aws-adfs-cli-mfa\mfa-saml.py')
    #child = pexpect.popen_spawn.PopenSpawn('python mfa-saml.py')
    child = wexpect.spawn('python mfa-saml.py')
    child.expect('Username')
    print(child.before, end='')
    print(child.after, end='')
    child.sendline('ypayalam@gbm.com.mx')
    #child.sendline('')
    child.expect('Password:')
    print(child.before, end='')
    print(child.after, end='')
    child.sendline('P@1v$051#.')
    child.expect('')
    print(child.before, end='')
    print(child.after, end='')
    child.sendline('')
    child.expect('Selection')
    print(child.before, end='')
    print(child.after, end='')
    child.sendline('1')
    child.expect('\n')
    print(child.before, end='')
    print(child.after, end='')
    child.wait()
except:
    print('Exception was thrown')
    print('debug information:')
    print(str(child))
